# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mywindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.frame_size = self.frame_width, self.frame_height = (900, 600)
        MainWindow.resize(self.frame_width, self.frame_height)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 900, 600))
        self.stackedWidget.setMinimumSize(QtCore.QSize(600, 400))
        self.stackedWidget.setMaximumSize(QtCore.QSize(2560, 1440))
        self.stackedWidget.setObjectName("stackedWidget")

        self.main_menu = QtWidgets.QWidget()
        self.main_menu.setObjectName("main_menu")

        self.verticalLayoutWidget = QtWidgets.QWidget(self.main_menu)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 100, 600, 400))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.button_currencies = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_currencies.sizePolicy().hasHeightForWidth())
        self.button_currencies.setSizePolicy(sizePolicy)
        self.button_currencies.setObjectName("button_currencies")
        self.verticalLayout.addWidget(self.button_currencies)

        self.button_key_rate_and_inflation = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_key_rate_and_inflation.sizePolicy().hasHeightForWidth())
        self.button_key_rate_and_inflation.setSizePolicy(sizePolicy)
        self.button_key_rate_and_inflation.setObjectName("button_key_rate_and_inflation")
        self.verticalLayout.addWidget(self.button_key_rate_and_inflation)

        self.button_gdp = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_gdp.sizePolicy().hasHeightForWidth())
        self.button_gdp.setSizePolicy(sizePolicy)
        self.button_gdp.setObjectName("button_gdp")
        self.verticalLayout.addWidget(self.button_gdp)

        self.stackedWidget.addWidget(self.main_menu)

        self.page_currencies = QtWidgets.QWidget()
        self.page_currencies.setObjectName("page_currencies")
        self.button_back_currencies = QtWidgets.QPushButton(self.page_currencies)
        self.button_back_currencies.setBaseSize(150, 100)
        self.button_back_currencies.setGeometry(20, self.frame_height - 100, 150, 50)
        self.stackedWidget.addWidget(self.page_currencies)

        self.page_key_rate = QtWidgets.QWidget()
        self.page_key_rate.setObjectName("page_key_rate")
        self.button_back_key_rate = QtWidgets.QPushButton(self.page_key_rate)
        self.button_back_key_rate.setBaseSize(150, 100)
        self.button_back_key_rate.setGeometry(20, self.frame_height-100, 150, 50)
        self.stackedWidget.addWidget(self.page_key_rate)

        self.page_gdp = QtWidgets.QWidget()
        self.page_gdp.setObjectName("page_gdp")
        self.button_back_gdp = QtWidgets.QPushButton(self.page_gdp)
        self.button_back_gdp.setBaseSize(150, 100)
        self.button_back_gdp.setGeometry(20, self.frame_height - 100, 150, 50)
        self.stackedWidget.addWidget(self.page_gdp)

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 894, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_currencies.setFont(QtGui.QFont('Times', 24))
        self.button_currencies.setText(_translate("MainWindow", "Валюты"))

        self.button_key_rate_and_inflation.setText(_translate("MainWindow", "Ключевая ставка и инфляция"))
        self.button_key_rate_and_inflation.setFont(QtGui.QFont('Times', 24))

        self.button_gdp.setText(_translate("MainWindow", "Внутренний Валовый Продукт"))
        self.button_gdp.setFont(QtGui.QFont('Times', 24))

        self.button_back_currencies.setText(_translate("MainWindow", "Назад"))
        self.button_back_currencies.setFont(QtGui.QFont('Times', 24))
        self.button_back_key_rate.setText(_translate("MainWindow", "Назад"))
        self.button_back_key_rate.setFont(QtGui.QFont('Times', 24))
        self.button_back_gdp.setText(_translate("MainWindow", "Назад"))
        self.button_back_gdp.setFont(QtGui.QFont('Times', 24))

        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.action.setText(_translate("MainWindow", "Обновить базу данных"))
